name: build-wireguard-tools
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - run: cd src && make -e LDFLAGS=-static && make install -e DESTDIR=/tmp

