name: linux-build
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:22.04
    steps:
    - uses: actions/checkout@v3
    - run: apt update && apt install build-essential && cd src && make
