name: ubuntu-build

on: [push]

jobs:
  Build-for-Ubuntu:
    name: Build for Ubuntu
    runs-on: ubuntu-latest
    container:
      image: ubuntu:22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build AmneziaWG tools
      run: |
        apt -y update &&
        apt -y install build-essential &&
        cd src &&
        make &&
        mkdir build &&
        cp wg ./build/wg &&
        cp wg-quick/linux.bash ./build/wg-quick

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ubuntu-22.04-amneziawg-tools
        path: ./src/build

  GitHub-Release:
    name: GitHub Release
    needs: Build-for-Ubuntu
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4

      - name: Calculate checksums
        run: |
          pwd &&
          ls -l &&
          for file in $(find ./ -type f); do openssl dgst -sha256 -r "$file" | awk '{print $1}' > "${file}.sha256"; done
        
      - name: Zip files
        run: ls -l

      - name: Upload binaries to Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./ubuntu-22.04-amneziawg-tools/wg
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
